version: '3.8'

services:
  bdu-hub:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bdu-tu-hoc-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./temp:/app/temp
