export const POS_CANONICAL = [
  'noun',
  'verb',
  'adjective',
  'adverb',
  'preposition',
  'pronoun',
  'conjunction',
  'determiner',
  'interjection',
  'modal verb',
  'auxiliary verb',
  'number'
];

export const POS_CATEGORY = [
  'phrase',
  'phrasal verb',
  'idiom',
  'collocation',
  'structure',
  'proper noun',
  'noun phrase',
  'verb phrase',
  'adjective phrase',
  'adverb phrase'
];

export const POS_ALIASES = {
  n: 'noun',
  'n pl': 'noun',
  'danh từ': 'noun',
  'danh từ riêng': 'proper noun',
  'danh từ số ít': 'noun',
  'danh từ số nhiều': 'noun',
  v: 'verb',
  'động từ': 'verb',
  'danh động từ': 'verb',
  'ngoại động từ': 'verb',
  'nội động từ': 'verb',
  'động từ nguyên thể': 'verb',
  'động từ - ngoại động từ': 'verb',
  'động từ - nội động từ': 'verb',
  'động từ - cả hai': 'verb',
  adj: 'adjective',
  'tính từ': 'adjective',
  adv: 'adverb',
  'trạng từ': 'adverb',
  'phó từ': 'adverb',
  'trạng ngữ': 'adverb',
  'trạng từ liên kết': 'adverb',
  prep: 'preposition',
  'giới từ': 'preposition',
  pron: 'pronoun',
  'đại từ': 'pronoun',
  conj: 'conjunction',
  'liên từ': 'conjunction',
  det: 'determiner',
  'mạo từ': 'determiner',
  'hạn định từ': 'determiner',
  'từ hạn định': 'determiner',
  interj: 'interjection',
  excl: 'interjection',
  'thán từ': 'interjection',
  num: 'number',
  'số': 'number',
  'số từ': 'number',
  aux: 'auxiliary verb',
  'trợ động từ': 'auxiliary verb',
  modal: 'modal verb',
  'động từ khuyết thiếu': 'modal verb',
  'động từ khiếm khuyết': 'modal verb',
  'phr v': 'phrasal verb',
  'cụm động từ': 'phrasal verb',
  'noun phr': 'noun phrase',
  'n phr': 'noun phrase',
  'n phrase': 'noun phrase',
  'cụm danh từ': 'noun phrase',
  'verb phr': 'verb phrase',
  'v. phrase': 'verb phrase',
  'cụm động từ nguyên thể': 'verb phrase',
  'adj phr': 'adjective phrase',
  'adj phrase': 'adjective phrase',
  'cụm tính từ': 'adjective phrase',
  'adv phr': 'adverb phrase',
  'cụm trạng từ': 'adverb phrase',
  'cụm từ': 'phrase',
  'cụm giới từ': 'phrase',
  'prep phrase': 'phrase',
  'thành ngữ': 'idiom',
  'tục ngữ': 'idiom',
  'cấu trúc': 'structure'
};

export const FUNCTION_WORD_POS = {
  i: ['pronoun'],
  me: ['pronoun'],
  you: ['pronoun'],
  he: ['pronoun'],
  him: ['pronoun'],
  she: ['pronoun'],
  her: ['pronoun', 'determiner'],
  it: ['pronoun'],
  we: ['pronoun'],
  us: ['pronoun'],
  they: ['pronoun'],
  them: ['pronoun'],
  myself: ['pronoun'],
  yourself: ['pronoun'],
  himself: ['pronoun'],
  herself: ['pronoun'],
  itself: ['pronoun'],
  ourselves: ['pronoun'],
  yourselves: ['pronoun'],
  themselves: ['pronoun'],
  oneself: ['pronoun'],
  who: ['pronoun'],
  whom: ['pronoun'],
  whose: ['pronoun', 'determiner'],
  whoever: ['pronoun'],
  whomever: ['pronoun'],
  someone: ['pronoun'],
  somebody: ['pronoun'],
  anyone: ['pronoun'],
  anybody: ['pronoun'],
  everyone: ['pronoun'],
  everybody: ['pronoun'],
  nobody: ['pronoun'],
  something: ['pronoun'],
  anything: ['pronoun'],
  nothing: ['pronoun'],
  everything: ['pronoun'],
  none: ['pronoun'],
  mine: ['pronoun', 'noun', 'verb'],
  yours: ['pronoun'],
  his: ['determiner', 'pronoun'],
  hers: ['pronoun'],
  its: ['determiner', 'pronoun'],
  ours: ['pronoun'],
  theirs: ['pronoun'],
  my: ['determiner', 'pronoun'],
  your: ['determiner', 'pronoun'],
  our: ['determiner', 'pronoun'],
  their: ['determiner', 'pronoun'],
  this: ['determiner', 'pronoun'],
  that: ['determiner', 'pronoun', 'conjunction'],
  these: ['determiner', 'pronoun'],
  those: ['determiner', 'pronoun'],
  which: ['pronoun', 'determiner'],
  whichever: ['pronoun', 'determiner'],
  what: ['pronoun', 'determiner'],
  whatever: ['pronoun', 'determiner', 'adverb'],

  a: ['determiner'],
  an: ['determiner'],
  the: ['determiner'],
  each: ['determiner', 'pronoun', 'adverb', 'adjective'],
  every: ['determiner'],
  either: ['determiner', 'pronoun', 'adverb', 'conjunction'],
  neither: ['determiner', 'pronoun', 'adverb', 'conjunction'],
  both: ['determiner', 'pronoun'],
  all: ['determiner', 'pronoun', 'adverb', 'adjective'],
  any: ['determiner', 'pronoun', 'adverb'],
  some: ['determiner', 'pronoun'],
  no: ['determiner', 'adverb', 'interjection'],
  many: ['determiner', 'pronoun'],
  much: ['determiner', 'pronoun', 'adverb'],
  more: ['determiner', 'pronoun', 'adverb'],
  most: ['determiner', 'pronoun', 'adverb'],
  few: ['determiner', 'pronoun', 'adjective'],
  little: ['determiner', 'pronoun', 'adjective', 'adverb', 'noun'],
  enough: ['determiner', 'pronoun', 'adverb', 'adjective', 'noun'],
  far: ['adverb', 'adjective'],
  several: ['determiner', 'pronoun', 'adjective'],
  another: ['determiner', 'pronoun'],
  other: ['determiner', 'pronoun', 'adjective'],
  such: ['determiner', 'pronoun', 'adjective'],
  half: ['determiner', 'pronoun', 'noun', 'adjective', 'adverb'],
  one: ['number', 'determiner', 'pronoun'],

  aboard: ['preposition', 'adverb'],
  about: ['preposition', 'adverb', 'adjective'],
  above: ['preposition', 'adverb', 'adjective'],
  across: ['preposition', 'adverb'],
  after: ['preposition', 'conjunction', 'adverb', 'adjective'],
  against: ['preposition'],
  along: ['preposition', 'adverb'],
  amid: ['preposition'],
  amidst: ['preposition'],
  among: ['preposition'],
  amongst: ['preposition'],
  around: ['preposition', 'adverb'],
  as: ['preposition', 'conjunction', 'adverb'],
  at: ['preposition'],
  atop: ['preposition'],
  before: ['preposition', 'conjunction', 'adverb'],
  behind: ['preposition', 'adverb', 'noun'],
  below: ['preposition', 'adverb', 'adjective'],
  beneath: ['preposition', 'adverb'],
  beside: ['preposition'],
  besides: ['preposition', 'adverb'],
  between: ['preposition', 'adverb'],
  beyond: ['preposition', 'adverb', 'noun'],
  but: ['conjunction', 'preposition'],
  by: ['preposition', 'adverb'],
  circa: ['preposition', 'adverb'],
  concerning: ['preposition'],
  considering: ['preposition', 'conjunction'],
  despite: ['preposition'],
  down: ['adverb', 'preposition', 'adjective', 'noun', 'verb'],
  during: ['preposition'],
  except: ['preposition', 'conjunction'],
  excluding: ['preposition'],
  following: ['preposition', 'adjective', 'noun', 'verb'],
  for: ['preposition', 'conjunction'],
  from: ['preposition'],
  given: ['preposition', 'adjective', 'verb'],
  in: ['preposition', 'adverb', 'adjective', 'noun'],
  including: ['preposition'],
  inside: ['preposition', 'adverb', 'adjective', 'noun'],
  into: ['preposition'],
  like: ['preposition', 'verb', 'noun', 'conjunction', 'adjective'],
  minus: ['preposition', 'noun', 'adjective'],
  near: ['preposition', 'adverb', 'adjective', 'verb'],
  of: ['preposition'],
  off: ['adverb', 'preposition', 'adjective', 'noun', 'verb'],
  on: ['preposition', 'adverb', 'adjective'],
  onto: ['preposition'],
  opposite: ['preposition', 'adjective', 'noun', 'adverb'],
  out: ['adverb', 'preposition', 'adjective', 'noun', 'verb'],
  outside: ['preposition', 'adverb', 'noun', 'adjective'],
  over: ['preposition', 'adverb', 'adjective', 'noun'],
  past: ['preposition', 'noun', 'adjective', 'adverb'],
  pending: ['preposition', 'adjective'],
  per: ['preposition'],
  plus: ['preposition', 'conjunction', 'noun', 'adjective'],
  regarding: ['preposition'],
  round: ['preposition', 'adverb', 'adjective', 'noun', 'verb'],
  since: ['preposition', 'conjunction', 'adverb'],
  than: ['preposition', 'conjunction'],
  through: ['preposition', 'adverb', 'adjective'],
  throughout: ['preposition', 'adverb'],
  till: ['preposition', 'conjunction', 'noun', 'verb'],
  to: ['preposition', 'adverb'],
  toward: ['preposition', 'adverb'],
  towards: ['preposition'],
  under: ['preposition', 'adverb', 'adjective'],
  underneath: ['preposition', 'adverb', 'noun', 'adjective'],
  unlike: ['preposition', 'adjective'],
  until: ['preposition', 'conjunction'],
  unto: ['preposition'],
  up: ['adverb', 'preposition', 'adjective', 'noun', 'verb'],
  upon: ['preposition'],
  versus: ['preposition'],
  via: ['preposition'],
  with: ['preposition'],
  within: ['preposition', 'adverb'],
  without: ['preposition', 'adverb'],
  worth: ['preposition', 'adjective', 'noun'],

  and: ['conjunction'],
  although: ['conjunction'],
  because: ['conjunction'],
  if: ['conjunction', 'noun'],
  lest: ['conjunction'],
  nor: ['conjunction'],
  or: ['conjunction'],
  provided: ['conjunction', 'adjective', 'verb'],
  so: ['adverb', 'conjunction', 'pronoun', 'adjective'],
  though: ['conjunction', 'adverb'],
  unless: ['conjunction'],
  when: ['adverb', 'conjunction', 'pronoun', 'noun'],
  whenever: ['conjunction', 'adverb'],
  where: ['adverb', 'conjunction', 'pronoun', 'noun'],
  whereas: ['conjunction'],
  wherever: ['conjunction', 'adverb'],
  whether: ['conjunction'],
  while: ['conjunction', 'noun', 'verb', 'preposition'],
  yet: ['adverb', 'conjunction'],

  am: ['verb', 'auxiliary verb'],
  is: ['verb', 'auxiliary verb'],
  are: ['verb', 'auxiliary verb'],
  was: ['verb', 'auxiliary verb'],
  were: ['verb', 'auxiliary verb'],
  be: ['verb', 'auxiliary verb'],
  been: ['verb', 'auxiliary verb'],
  being: ['verb', 'noun', 'auxiliary verb'],
  have: ['verb', 'auxiliary verb'],
  has: ['verb', 'auxiliary verb'],
  had: ['verb', 'auxiliary verb'],
  having: ['verb', 'noun', 'auxiliary verb'],
  do: ['verb', 'auxiliary verb', 'noun'],
  does: ['verb', 'auxiliary verb', 'noun'],
  did: ['verb', 'auxiliary verb'],
  done: ['verb', 'adjective'],
  doing: ['verb', 'noun'],
  can: ['modal verb', 'noun', 'verb'],
  could: ['modal verb'],
  may: ['modal verb', 'noun'],
  might: ['modal verb', 'noun'],
  must: ['modal verb', 'noun'],
  shall: ['modal verb'],
  should: ['modal verb'],
  will: ['modal verb', 'noun', 'verb'],
  would: ['modal verb'],
  ought: ['modal verb'],

  not: ['adverb'],
  never: ['adverb'],
  always: ['adverb'],
  often: ['adverb'],
  sometimes: ['adverb', 'adjective'],
  usually: ['adverb'],
  already: ['adverb'],
  still: ['adverb', 'adjective', 'noun', 'verb'],
  just: ['adverb', 'adjective'],
  only: ['adverb', 'adjective', 'conjunction'],
  even: ['adverb', 'adjective', 'verb'],
  also: ['adverb'],
  too: ['adverb'],
  very: ['adverb', 'adjective'],
  quite: ['adverb', 'determiner'],
  rather: ['adverb', 'interjection'],
  really: ['adverb'],
  ever: ['adverb'],
  ago: ['adverb'],
  away: ['adverb', 'adjective'],
  back: ['adverb', 'noun', 'verb', 'adjective'],
  forth: ['adverb'],
  here: ['adverb', 'interjection'],
  there: ['adverb', 'pronoun', 'interjection', 'noun'],
  now: ['adverb', 'conjunction'],
  then: ['adverb', 'adjective', 'noun'],
  today: ['adverb', 'noun'],
  tomorrow: ['adverb', 'noun'],
  yesterday: ['adverb', 'noun'],
  tonight: ['adverb', 'noun'],
  soon: ['adverb'],
  once: ['adverb', 'conjunction', 'noun'],
  twice: ['adverb'],
  again: ['adverb'],
  maybe: ['adverb'],
  perhaps: ['adverb'],
  indeed: ['adverb'],
  instead: ['adverb'],
  anyway: ['adverb'],
  anyhow: ['adverb'],
  somehow: ['adverb'],
  somewhat: ['adverb', 'pronoun'],
  somewhere: ['adverb', 'pronoun'],
  anywhere: ['adverb', 'pronoun'],
  everywhere: ['adverb', 'pronoun'],
  nowhere: ['adverb', 'pronoun'],
  elsewhere: ['adverb'],
  sometime: ['adverb', 'adjective'],
  anytime: ['adverb'],
  nowadays: ['adverb'],
  upstairs: ['adverb', 'adjective', 'noun'],
  downstairs: ['adverb', 'adjective', 'noun'],
  abroad: ['adverb', 'adjective'],
  ahead: ['adverb', 'adjective'],
  apart: ['adverb', 'adjective'],
  aside: ['adverb', 'noun', 'preposition'],
  together: ['adverb', 'adjective'],
  alone: ['adverb', 'adjective'],
  hence: ['adverb'],
  thus: ['adverb'],
  therefore: ['adverb'],
  however: ['adverb', 'conjunction'],
  moreover: ['adverb'],
  nevertheless: ['adverb'],
  otherwise: ['adverb', 'adjective', 'conjunction'],
  henceforth: ['adverb'],
  how: ['adverb', 'conjunction'],
  why: ['adverb', 'conjunction', 'noun'],
  well: ['adverb', 'adjective', 'interjection'],

  hello: ['interjection', 'noun'],
  hi: ['interjection'],
  hey: ['interjection'],
  oh: ['interjection'],
  wow: ['interjection'],
  yes: ['interjection', 'noun'],
  yeah: ['interjection'],
  yep: ['interjection'],
  nope: ['interjection'],
  okay: ['interjection', 'adjective', 'adverb'],
  ok: ['interjection', 'adjective', 'adverb'],
  please: ['interjection', 'adverb', 'verb'],
  thanks: ['interjection', 'noun'],
  thank: ['verb', 'noun'],
  sorry: ['adjective', 'interjection'],
  goodbye: ['interjection', 'noun'],
  bye: ['interjection', 'noun'],
  alas: ['interjection'],
  oops: ['interjection'],
  ouch: ['interjection'],
  hooray: ['interjection'],
  huh: ['interjection'],
  um: ['interjection'],
  uh: ['interjection'],
  hmm: ['interjection'],

  zero: ['number', 'determiner'],
  two: ['number', 'noun'],
  three: ['number', 'noun'],
  four: ['number', 'noun'],
  five: ['number', 'noun'],
  six: ['number', 'noun'],
  seven: ['number', 'noun'],
  eight: ['number', 'noun'],
  nine: ['number', 'noun'],
  ten: ['number', 'noun'],
  eleven: ['number', 'noun'],
  twelve: ['number', 'noun'],
  thirteen: ['number'],
  fourteen: ['number'],
  fifteen: ['number'],
  sixteen: ['number'],
  seventeen: ['number'],
  eighteen: ['number'],
  nineteen: ['number'],
  twenty: ['number', 'noun'],
  thirty: ['number', 'noun'],
  forty: ['number', 'noun'],
  fifty: ['number', 'noun'],
  sixty: ['number'],
  seventy: ['number'],
  eighty: ['number'],
  ninety: ['number'],
  hundred: ['number', 'noun'],
  thousand: ['number', 'noun'],
  million: ['number', 'noun'],
  billion: ['number', 'noun'],
  first: ['number', 'adjective', 'adverb'],
  second: ['number', 'adjective', 'noun', 'adverb'],
  third: ['number', 'adjective', 'noun'],
  fourth: ['number', 'adjective', 'noun'],
  fifth: ['number', 'adjective', 'noun'],
  sixth: ['number', 'adjective'],
  seventh: ['number', 'adjective'],
  eighth: ['number', 'adjective'],
  ninth: ['number', 'adjective'],
  tenth: ['number', 'adjective']
};

function normalizeTerm(term) {
  return String(term ?? '').trim().toLowerCase();
}

export function normalizePosList(raw) {
  const unknown = [];
  const cleaned = String(raw ?? '')
    .replace(/\([^)]*\)?/g, ' ')
    .replace(/["'“”‘’]/g, ' ')
    .toLowerCase();
  const parts = cleaned.split(/[;,\/]|\s[-–—]\s/);
  const list = [];
  for (const part of parts) {
    const token = part.replace(/\s+/g, ' ').trim();
    if (!token) continue;
    const mapped = POS_ALIASES[token]
      || (POS_CANONICAL.includes(token) || POS_CATEGORY.includes(token) ? token : null);
    if (!mapped) {
      if (!unknown.includes(token)) unknown.push(token);
      continue;
    }
    if (!list.includes(mapped)) list.push(mapped);
  }
  return { list, unknown };
}

export function normalizePos(raw) {
  return normalizePosList(raw).list.join(', ').slice(0, 64);
}

export function inferPos(term) {
  const entry = FUNCTION_WORD_POS[normalizeTerm(term)];
  return entry ? entry[0] : null;
}

function lookupFunctionWord(term) {
  const trimmed = String(term ?? '').trim();
  if (!trimmed) return null;
  if (trimmed !== trimmed.toLowerCase() && trimmed !== 'I') return null;
  return FUNCTION_WORD_POS[trimmed.toLowerCase()] || null;
}

export function resolvePos(term, rawPos) {
  const { list } = normalizePosList(rawPos);
  const normalized = list.join(', ').slice(0, 64);
  const allowed = lookupFunctionWord(term);
  if (allowed) {
    const keepsRaw = list.length > 0 && list.every((pos) => allowed.includes(pos));
    if (!keepsRaw) return { pos: allowed[0], source: 'override' };
    return { pos: normalized, source: 'normalized' };
  }
  if (list.length > 0) return { pos: normalized, source: 'normalized' };
  const words = String(term ?? '').trim().split(/\s+/).filter(Boolean);
  if (words.length >= 2) return { pos: 'phrase', source: 'category' };
  return { pos: '', source: 'empty' };
}
