/**
 * Xuất dữ liệu tham chiếu vocab (themes/sets/words) từ DB local ra file SQL upsert
 * để nạp lên VPS — KHÔNG bao gồm vocab_progress (tiến độ của user trên prod).
 *
 * Chạy: node scripts/export-vocab.js [outPath=data/vocab-export.sql]
 * Nạp trên VPS:
 *   cat data/vocab-export.sql | docker compose exec -T postgres sh -lc 'psql -U "$POSTGRES_USER" -d "$POSTGRES_DB"'
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { closeDatabase, isDatabaseConfigured, query } from '../src/db/database.js';

const currentDir = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(currentDir, '..');
const outPath = path.resolve(rootDir, process.argv[2] || 'data/vocab-export.sql');
const BATCH = 400;

function q(value) {
  if (value === null || value === undefined) return 'NULL';
  return `'${String(value).replace(/'/g, "''")}'`;
}

function chunks(list, size) {
  const out = [];
  for (let i = 0; i < list.length; i += size) out.push(list.slice(i, i + size));
  return out;
}

if (!isDatabaseConfigured()) {
  console.error('Thiếu DATABASE_URL.');
  process.exit(1);
}

const themes = (await query('SELECT slug, luyentu_id, title, description, difficulty, total_sets FROM vocab_themes ORDER BY slug')).rows;
const sets = (await query('SELECT id, theme_slug, name, order_idx, vocab_count FROM vocab_sets ORDER BY theme_slug, order_idx')).rows;
const words = (await query('SELECT id, set_id, term, pronunciation, pos, meaning_vi, example, notes, audio_url, sort_order FROM vocab_words ORDER BY set_id, sort_order')).rows;

const lines = [];
lines.push('-- Vocab reference export (themes/sets/words) — generated by scripts/export-vocab.js');
lines.push(`-- Generated at ${new Date().toISOString()} | themes=${themes.length} sets=${sets.length} words=${words.length}`);
lines.push('BEGIN;');

for (const batch of chunks(themes, BATCH)) {
  const values = batch.map((r) => `(${q(r.slug)}, ${q(r.luyentu_id)}, ${q(r.title)}, ${q(r.description)}, ${Number(r.difficulty) || 1}, ${Number(r.total_sets) || 0})`).join(',\n  ');
  lines.push(`INSERT INTO vocab_themes (slug, luyentu_id, title, description, difficulty, total_sets) VALUES\n  ${values}\nON CONFLICT (slug) DO UPDATE SET luyentu_id=EXCLUDED.luyentu_id, title=EXCLUDED.title, description=EXCLUDED.description, difficulty=EXCLUDED.difficulty, total_sets=EXCLUDED.total_sets, updated_at=NOW();`);
}

for (const batch of chunks(sets, BATCH)) {
  const values = batch.map((r) => `(${q(r.id)}, ${q(r.theme_slug)}, ${q(r.name)}, ${Number(r.order_idx) || 0}, ${Number(r.vocab_count) || 0})`).join(',\n  ');
  lines.push(`INSERT INTO vocab_sets (id, theme_slug, name, order_idx, vocab_count) VALUES\n  ${values}\nON CONFLICT (id) DO UPDATE SET theme_slug=EXCLUDED.theme_slug, name=EXCLUDED.name, order_idx=EXCLUDED.order_idx, vocab_count=EXCLUDED.vocab_count, updated_at=NOW();`);
}

for (const batch of chunks(words, BATCH)) {
  const values = batch.map((r) => `(${q(r.id)}, ${q(r.set_id)}, ${q(r.term)}, ${q(r.pronunciation)}, ${q(r.pos)}, ${q(r.meaning_vi)}, ${q(r.example)}, ${q(r.notes)}, ${q(r.audio_url)}, ${Number(r.sort_order) || 0})`).join(',\n  ');
  lines.push(`INSERT INTO vocab_words (id, set_id, term, pronunciation, pos, meaning_vi, example, notes, audio_url, sort_order) VALUES\n  ${values}\nON CONFLICT (id) DO UPDATE SET term=EXCLUDED.term, pronunciation=EXCLUDED.pronunciation, pos=EXCLUDED.pos, meaning_vi=EXCLUDED.meaning_vi, example=EXCLUDED.example, notes=EXCLUDED.notes, audio_url=EXCLUDED.audio_url, sort_order=EXCLUDED.sort_order;`);
}

lines.push('COMMIT;');
lines.push('');

await fs.mkdir(path.dirname(outPath), { recursive: true });
await fs.writeFile(outPath, lines.join('\n'), 'utf-8');
await closeDatabase();
console.log(`✓ Exported ${themes.length} themes, ${sets.length} sets, ${words.length} words -> ${outPath}`);
