/**
 * Xuất dữ liệu tham chiếu ngữ pháp (groups/paths/lessons/rules/exercises/reading)
 * từ DB local ra file SQL upsert để nạp lên VPS — KHÔNG bao gồm grammar_progress
 * (tiến độ học của user trên prod).
 *
 * Chạy: npm run grammar:export (hoặc node scripts/export-grammar.js [outPath])
 * Nạp trên VPS:
 *   cat data/grammar-export.sql | docker compose exec -T postgres sh -lc 'psql -U "$POSTGRES_USER" -d "$POSTGRES_DB"'
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { closeDatabase, isDatabaseConfigured, query } from '../src/db/database.js';

const currentDir = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(currentDir, '..');
const outPath = path.resolve(rootDir, process.argv[2] || 'data/grammar-export.sql');
const BATCH = 200;

function q(value) {
  if (value === null || value === undefined) return 'NULL';
  return `'${String(value).replace(/'/g, "''")}'`;
}

function chunks(list, size) {
  const out = [];
  for (let i = 0; i < list.length; i += size) out.push(list.slice(i, i + size));
  return out;
}

if (!isDatabaseConfigured()) {
  console.error('Thiếu DATABASE_URL.');
  process.exit(1);
}

const groups = (await query('SELECT id, name, order_idx FROM grammar_groups ORDER BY order_idx, name')).rows;
const paths = (await query(
  `SELECT id, group_id, slug, name, description, cover_image, difficulty, banner_label, badge_label,
          order_idx, lesson_count, question_count
   FROM grammar_paths ORDER BY order_idx, name`
)).rows;
const lessons = (await query(
  `SELECT id, path_id, name, description, order_idx, question_count
   FROM grammar_lessons ORDER BY path_id, order_idx, name`
)).rows;
const rules = (await query(
  'SELECT id, lesson_id, title, content, order_idx FROM grammar_rules ORDER BY lesson_id, order_idx, id'
)).rows;
const exercises = (await query(
  `SELECT id, lesson_id, type, question, option_a, option_b, option_c, option_d,
          correct_answer, correct_option, explanation, hint, order_idx
   FROM grammar_exercises ORDER BY lesson_id, order_idx, id`
)).rows;
const readings = (await query(
  'SELECT id, lesson_id, title, passage, order_idx FROM grammar_reading_exercises ORDER BY lesson_id, order_idx, id'
)).rows;
const readingQuestions = (await query(
  `SELECT id, reading_id, type, question, option_a, option_b, option_c, option_d,
          correct_answer, correct_option, explanation, order_idx
   FROM grammar_reading_questions ORDER BY reading_id, order_idx, id`
)).rows;

const lines = [];
lines.push('-- Grammar reference export (groups/paths/lessons/rules/exercises/reading) — generated by scripts/export-grammar.js');
lines.push(`-- Generated at ${new Date().toISOString()} | groups=${groups.length} paths=${paths.length} lessons=${lessons.length} rules=${rules.length} exercises=${exercises.length} readings=${readings.length} reading_questions=${readingQuestions.length}`);
lines.push('BEGIN;');

for (const batch of chunks(groups, BATCH)) {
  const values = batch.map((r) => `(${q(r.id)}, ${q(r.name)}, ${Number(r.order_idx) || 0})`).join(',\n  ');
  lines.push(`INSERT INTO grammar_groups (id, name, order_idx) VALUES\n  ${values}\nON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name, order_idx=EXCLUDED.order_idx, updated_at=NOW();`);
}

for (const batch of chunks(paths, BATCH)) {
  const values = batch.map((r) => `(${q(r.id)}, ${q(r.group_id)}, ${q(r.slug)}, ${q(r.name)}, ${q(r.description)}, ${q(r.cover_image)}, ${Number(r.difficulty) || 1}, ${q(r.banner_label)}, ${q(r.badge_label)}, ${Number(r.order_idx) || 0}, ${Number(r.lesson_count) || 0}, ${Number(r.question_count) || 0})`).join(',\n  ');
  lines.push(`INSERT INTO grammar_paths (id, group_id, slug, name, description, cover_image, difficulty, banner_label, badge_label, order_idx, lesson_count, question_count) VALUES\n  ${values}\nON CONFLICT (id) DO UPDATE SET group_id=EXCLUDED.group_id, slug=EXCLUDED.slug, name=EXCLUDED.name, description=EXCLUDED.description, cover_image=EXCLUDED.cover_image, difficulty=EXCLUDED.difficulty, banner_label=EXCLUDED.banner_label, badge_label=EXCLUDED.badge_label, order_idx=EXCLUDED.order_idx, lesson_count=EXCLUDED.lesson_count, question_count=EXCLUDED.question_count, updated_at=NOW();`);
}

for (const batch of chunks(lessons, BATCH)) {
  const values = batch.map((r) => `(${q(r.id)}, ${q(r.path_id)}, ${q(r.name)}, ${q(r.description)}, ${Number(r.order_idx) || 0}, ${Number(r.question_count) || 0})`).join(',\n  ');
  lines.push(`INSERT INTO grammar_lessons (id, path_id, name, description, order_idx, question_count) VALUES\n  ${values}\nON CONFLICT (id) DO UPDATE SET path_id=EXCLUDED.path_id, name=EXCLUDED.name, description=EXCLUDED.description, order_idx=EXCLUDED.order_idx, question_count=EXCLUDED.question_count, updated_at=NOW();`);
}

for (const batch of chunks(rules, BATCH)) {
  const values = batch.map((r) => `(${q(r.id)}, ${q(r.lesson_id)}, ${q(r.title)}, ${q(r.content)}, ${Number(r.order_idx) || 0})`).join(',\n  ');
  lines.push(`INSERT INTO grammar_rules (id, lesson_id, title, content, order_idx) VALUES\n  ${values}\nON CONFLICT (id) DO UPDATE SET lesson_id=EXCLUDED.lesson_id, title=EXCLUDED.title, content=EXCLUDED.content, order_idx=EXCLUDED.order_idx;`);
}

for (const batch of chunks(exercises, BATCH)) {
  const values = batch.map((r) => `(${q(r.id)}, ${q(r.lesson_id)}, ${q(r.type)}, ${q(r.question)}, ${q(r.option_a)}, ${q(r.option_b)}, ${q(r.option_c)}, ${q(r.option_d)}, ${q(r.correct_answer)}, ${q(r.correct_option)}, ${q(r.explanation)}, ${q(r.hint)}, ${Number(r.order_idx) || 0})`).join(',\n  ');
  lines.push(`INSERT INTO grammar_exercises (id, lesson_id, type, question, option_a, option_b, option_c, option_d, correct_answer, correct_option, explanation, hint, order_idx) VALUES\n  ${values}\nON CONFLICT (id) DO UPDATE SET lesson_id=EXCLUDED.lesson_id, type=EXCLUDED.type, question=EXCLUDED.question, option_a=EXCLUDED.option_a, option_b=EXCLUDED.option_b, option_c=EXCLUDED.option_c, option_d=EXCLUDED.option_d, correct_answer=EXCLUDED.correct_answer, correct_option=EXCLUDED.correct_option, explanation=EXCLUDED.explanation, hint=EXCLUDED.hint, order_idx=EXCLUDED.order_idx;`);
}

for (const batch of chunks(readings, BATCH)) {
  const values = batch.map((r) => `(${q(r.id)}, ${q(r.lesson_id)}, ${q(r.title)}, ${q(r.passage)}, ${Number(r.order_idx) || 0})`).join(',\n  ');
  lines.push(`INSERT INTO grammar_reading_exercises (id, lesson_id, title, passage, order_idx) VALUES\n  ${values}\nON CONFLICT (id) DO UPDATE SET lesson_id=EXCLUDED.lesson_id, title=EXCLUDED.title, passage=EXCLUDED.passage, order_idx=EXCLUDED.order_idx;`);
}

for (const batch of chunks(readingQuestions, BATCH)) {
  const values = batch.map((r) => `(${q(r.id)}, ${q(r.reading_id)}, ${q(r.type)}, ${q(r.question)}, ${q(r.option_a)}, ${q(r.option_b)}, ${q(r.option_c)}, ${q(r.option_d)}, ${q(r.correct_answer)}, ${q(r.correct_option)}, ${q(r.explanation)}, ${Number(r.order_idx) || 0})`).join(',\n  ');
  lines.push(`INSERT INTO grammar_reading_questions (id, reading_id, type, question, option_a, option_b, option_c, option_d, correct_answer, correct_option, explanation, order_idx) VALUES\n  ${values}\nON CONFLICT (id) DO UPDATE SET reading_id=EXCLUDED.reading_id, type=EXCLUDED.type, question=EXCLUDED.question, option_a=EXCLUDED.option_a, option_b=EXCLUDED.option_b, option_c=EXCLUDED.option_c, option_d=EXCLUDED.option_d, correct_answer=EXCLUDED.correct_answer, correct_option=EXCLUDED.correct_option, explanation=EXCLUDED.explanation, order_idx=EXCLUDED.order_idx;`);
}

lines.push('COMMIT;');
lines.push('');

await fs.mkdir(path.dirname(outPath), { recursive: true });
await fs.writeFile(outPath, lines.join('\n'), 'utf-8');
await closeDatabase();
console.log(`✓ Exported ${groups.length} groups, ${paths.length} paths, ${lessons.length} lessons, ${rules.length} rules, ${exercises.length} exercises, ${readings.length} readings, ${readingQuestions.length} reading questions -> ${outPath}`);
